### ISSUE TITLE
Kibana does not work with api_keys

### ISSUE THREAD

**Issue by staticdev** [beshu-tech/readonlyrest-docs#20]
I am using ReadonlyREST Free (ES) to force users to pass an api key for every request.
I've tried with versions 6.5.4 of Kibana, ES and plugin readonlyrest-1.16.33_es6.5.4.zip and also Kibana ES 6.2.4 with readonlyrest-1.16.33_es6.2.4.zip.

My readonlyrest.yml:

```
readonlyrest:
    response_if_req_forbidden: "NOT ALLOWED!"
    access_control_rules:
    - name: "Accept all requests from localhost"
      type: allow
      hosts: [127.0.0.1]
      uri_re: ^/*

    - name: "Read key"
      type: allow
      api_keys: [myreadkey]
      methods: [GET]

    - name: "Write key"
      type: allow
      api_keys: [mywritekey]
```

It works for my REST quests:

`curl -H 'X-Api-Key: myreadkey' http://10.XXX.XXX.XXX:9200/logs/_search?`

kibana.yml has elasticsearch.customHeaders set to {"X-Api-Key":"myreadkey"}.

The problem is that Kibana does not work. Is there a way to configure Kibana to pass the keys for all of its requests? Do I have to create another kibana_access rule? How does it knows it really is Kibana calling? What is the recommended procedure in this case?
