### ISSUE TITLE
Issue while installing ROR on Kubernetes via HelmCharts

### ISSUE THREAD

**Issue by mukeshchouhan** [beshu-tech/readonlyrest-docs#33]
Docker file to create image with ROR -

```
FROM dfw-gteo-hub-docker.prod.walmart.com:5000/elasticsearch:7.4.2
COPY --chown=elasticsearch:elasticsearch readonlyrest-1.18.9_es7.4.2.zip /tmp
WORKDIR /usr/share/elasticsearch
RUN bin/elasticsearch-plugin install --batch file:///tmp/readonlyrest-1.18.9_es7.4.2.zip
COPY --chown=elasticsearch:elasticsearch readonlyrest.yml /usr/share/elasticsearch/config
```

readonlyrest.yml

```
readonlyrest:
    #optional
    enable: true
    response_if_req_forbidden: Sorry, your request is forbidden by ReadonlyREST ES plugin

    access_control_rules:
    # We trust Kibana's server side process, full access granted via HTTP authentication
    - name: "::KIBANA-SRV::"
      auth_key: kibana:kibana
      verbosity: error # don't log successful request

    - name: "::RO DEVELOPER::"
      auth_key: readonly:readonly
      kibana_access: ro_strict
      indices: ["*"]

    - name: "::RW::"
      auth_key: readwrite:asd321
      kibana_access: rw
      indices: ["*"]

    - name: "public access monitoring"
      actions: ["indices:data/read/search"]
      indices: [".monitoring*"]

    - name: "Public Access Custom"
      actions: ["indices:data/read/field_stats", "indices:admin/mappings/fields/get", "indices:admin/get", "indices:data/read/msearch", "indices:data/read/field_caps"]
      indices: ["*"]
```

Sample HelmChart -
`https://github.com/elastic/helm-charts/blob/master/elasticsearch/values.yaml`

Getting below message in pod logs  -

`{"type": "server", "timestamp": "2019-12-02T15:22:50,189Z", "level": "INFO", "component": "t.b.r.a.l.AccessControlLoggingDecorator", "cluster.name": "mycluster", "node.name": "master-4", "message": "\u001B[35mFORBIDDEN by default req={  ID:239623908-1322721299#565,  TYP:ClusterHealthRequest,  CGR:N/A,  USR:[user not logged],  BRS:true,  KDX:null,  ACT:cluster:monitor/health,  OA:127.0.0.1/32,  XFF:null,  DA:127.0.0.1/32,  IDX:<N/A>,  MET:GET,  PTH:/_cluster/health,  CNT:<N/A>,  HDR:Accept=*/*, Host=127.0.0.1:9200, User-Agent=curl/7.29.0, content-length=0,  HIS:[::KIBANA-SRV::-> RULES:[auth_key->false], RESOLVED:[]], [::RO DEVELOPER::-> RULES:[auth_key->false], RESOLVED:[]], [::RW::-> RULES:[auth_key->false], RESOLVED:[]], [public access monitoring-> RULES:[indices->true, actions->false], RESOLVED:[indices=.monitoring-kibana-7-2019.11.29,.monitoring-kibana-7-2019.11.28,.monitoring-kibana-7-2019.11.30,.monitoring-es-7-2019.11.27,.monitoring-kibana-7-2019.11.26,.monitoring-es-7-2019.11.29,.monitoring-es-7-2019.11.30,.monitoring-es-7-2019.12.02,.monitoring-es-7-2019.11.28,.monitoring-kibana-7-2019.12.01,.monitoring-es-7-2019.11.26,.monitoring-es-7-2019.12.01,.monitoring-kibana-7-2019.11.27,.monitoring-kibana-7-2019.12.02]], [Public Access Custom-> RULES:[indices->true, actions->false], RESOLVED:[]]  }\u001B[0m", "cluster.uuid": "YsS3RfyoTvmAw6U8LEu9Tw", "node.id": "l1KKSm89RhW8Qo_MrDVyZw"  }`

POD is not coming up -

`master-4  0/1    Running   0         47m`

Can you please help me with this?
